[workspace]
members = ["aeron-rs"]
resolver = "2"

[workspace.dependencies]
thiserror = "1.0"
rand = "0.8"
ctrlc = "3.4"
log = "0.4"
pretty_env_logger = "0.5"
galvanic-assert = "0.8"
chrono = "0.4"
core_affinity = "0.8.1"
cache_line_size = "1.0.0"
memoffset = "0.9"
num-traits = "0.2"
lazy_static = "1.4"
memmap = "0.7"
nix = { version = "0.29" }

[build]
target-dir = "target"

[workspace.lints.rust]
missing_docs = "allow"
# missing_docs = "deny"
unused_crate_dependencies = "warn"
