[package]
name = "aeron_archiver_codecs"
version = "0.1.0"
authors = ["sbetool"]
description = "Message Codecs for communicating with an Aeron Archive."
edition = "2021"

[lib]
name = "aeron_archiver_codecs"
path = "src/lib.rs"
