name: Rust

on:
  push:
    branches: [ "archive-support" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install SBE Schema
      run: cargo install --git https://github.com/rafalpiotrowski/sbe-schema
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
